baseURL = 'https://mathfagraad.dk/'
languageCode = 'da-DK'
title = 'Det Fællesmatematiske Fagråd'
theme = 'ananke'
enableGitInfo = true
googleAnalytics = 'G-1TXN9FWSRB'

[params]
  mainSections = ["posts"]
  githublink = "https://github.com/Det-Faellesmatematiske-Fagrad/det-faellesmatematiske-fagrad.github.io/blob/main/content/"
  body_classes = "bg-near-white"
  site_logo = "img/logo.png"
  favicon = "favicon-32x32.png"
  [[params.ananke_socials]]
    name = "facebook"
    url = "https://www.facebook.com/MatematiskFagraad"

  [[params.ananke_socials]]
    name = "github"
    url = "https://github.com/Det-Faellesmatematiske-Fagrad"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
