baseURL = 'https://mathfagraad.dk/'
languageCode = 'da-DK'
title = 'Det Fællesmatematiske Fagråd'
theme = 'ananke'

[params]
  site_logo = "img/logo.png"
  favicon = "favicon-32x32.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
